#!/usr/bin/env bash

set -e

app_name="$1"
table_name="$2"

usage() {
  echo "Usage: $0 HEROKU_APP_NAME POSTGRES_TABLE_NAME"
}

[ -z $app_name ] && {
  echo "APP_NAME is missing" >&2
  usage
  exit 1
}

[ -z $table_name ] && {
  echo "TABLE_NAME is missing" >&2
  usage
  exit 1
}

eval $(heroku config:get -s DATABASE_URL KAFKA_URL -a "$app_name")

url_re='^postgres://([[:alnum:]]+):([[:alnum:]]+)@([-\.[:alnum:]]+):([[:digit:]]+)/([[:alnum:]]+)'
if [[ $DATABASE_URL =~ $url_re ]]; then
  user=${BASH_REMATCH[1]}
  pass=${BASH_REMATCH[2]}
  host=${BASH_REMATCH[3]}
  port=${BASH_REMATCH[4]}
  database=${BASH_REMATCH[5]}
fi

# cat <<JSON
curl -X POST -H "Content-Type: application/json" -d @- https://${app_name}.herokuapp.com/connectors <<JSON
{
  "name": "demo-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "tasks.max": "1",
    "database.hostname": "${host}",
    "database.port": "${port}",
    "database.user": "${user}",
    "database.password": "${pass}",
    "database.dbname" : "${database}",
    "database.server.name": "${host}",
    "database.whitelist": "${table_name}",
    "database.history.kafka.bootstrap.servers": "${KAFKA_URL//kafka+ssl:\/\//}",
    "database.history.kafka.topic": "schema-changes.${table_name}"
  }
}
JSON
