#!/usr/bin/env bash

KSQL_PROPERTIES_FILE="ksql-server.properties"
KSQL_URL="https://github.com/confluentinc/ksql/releases/download/v0.4/ksql-0.4.tgz"

./setup_certs HEROKU_KAFKA_JCHAO

cat > $KSQL_PROPERTIES_FILE <<PROPERTIES
security.protocol=SSL
ssl.truststore.location=$HOME/.truststore.jks
ssl.truststore.password=$TRUSTSTORE_PASSWORD
ssl.keystore.location=$HOME/.keystore.jks
ssl.keystore.password=$KEYSTORE_PASSWORD
ssl.key.password=$KEYSTORE_PASSWORD

bootstrap.servers=${HEROKU_KAFKA_JCHAO_URL//kafka+ssl:\/\//}

application.id=ksql-cluster

listeners=http://0.0.0.0:$PORT

PROPERTIES

wget -qO - $KSQL_URL | tar -zxf -
if ! [ $? ]; then
  echo "could not download ksql package"
fi

cp ksql/bin/* .apt/usr/bin
mkdir .apt/usr/share/java/ksql
cp ksql/share/java/ksql/*.jar .apt/usr/share/java/ksql
mkdir .apt/etc/ksql
cp ksql/config/* .apt/etc/ksql

KAFKA_HEAP_OPTS="-Xms1g -Xmx1g" .apt/usr/bin/ksql-server-start $KSQL_PROPERTIES_FILE
